### ISSUE TITLE
No mapping for the Unicode character

### ISSUE THREAD

**Issue by Friendlyman66** [AirGuanZ/imgui-filebrowser#11]
Sup, i have a small problem, every time i try to go to "AppData\Local" i get a "No mapping for the Unicode character exists in the target..." I was trying to find a solution for like 3 hours before but i didn't figure out anything.

**Comment by AirGuanZ** [comment]
hi, i failed to reproduce the problem on my pc. i guess it's caused by a file/dir with a name containing uncommon character(s). is it a message shown on the status bar or an exception?

**Comment by AirGuanZ** [comment]
i tried to fix the problem (without testing because i cannot reproduce the problem). please try the new version

**Comment by Friendlyman66** [comment]
Yeah, it works perfectly now! Thanks, i didn't expect the respond that fast. Thank you so much again.
