### ISSUE TITLE
no operator "+" matches these operands

### ISSUE THREAD

**Issue by kaceros90** [AirGuanZ/imgui-filebrowser#14]
error: no operator "+" matches these operands

code: [imgur](https://imgur.com/9y2RcSg)

**Comment by AirGuanZ** [comment]
`std::filesystem::path::u8string()` returns an object of type `std::string`, so it should be ok to use `operator+` to cat a `const char*` with `std::string`... I'm not sure why this ce happens. Maybe it's caused by compiler config. Could you please setup a new project and test the following code?

```cpp
#include <iostream>
#include <filesystem>

int main()
{
    std::cout << ("test output" + std::filesystem::current_path().u8string() + "  test output") << std::endl;
}
```

**Comment by kaceros90** [comment]
Okay thanks for help, I had to change only C++ Language standard to ISO C++ 17 standard(std:c++17)
