### ISSUE TITLE
File Browser does not open

### ISSUE THREAD

**Issue by kaceros90** [AirGuanZ/imgui-filebrowser#15]
I have another problem..
File Browser do not open only in FiveM, but in the directx11 test window the file browser already opens... how to solve it?

**Comment by AirGuanZ** [comment]
Sorry but could you describe the problem in more detail? Do you means you want to open the file browser in another window rather than the one with imgui context associated with?

**Comment by mattlacey** [comment]
Might be a dumb suggestion - but I thought it wasn't working and then realised I'd borrowed the example code and it was opening off-screen for my small app window.
