### ISSUE TITLE
Only compiles with C++17

### ISSUE THREAD

**Issue by higaski** [AirGuanZ/imgui-filebrowser#17]
C++17 is the only standard this header can be compiled with. Anything below has no filesystem support and anything above (so currently only C++20) complains about char8_t not being convertible to char.

**Comment by AirGuanZ** [comment]
3rd-party/hand-write filesystem support is not in the current plan, And ce with c++20 is caused by std changes on std::fs::path::u8string.
Tks for telling me this. I have added a conversion for it.

**Comment by higaski** [comment]
Wow that was fast thank you.
For the record, I wasn't complaining that it requires C++17, just that it broke again with C++20. :)
