### ISSUE TITLE
How do I open a directory/folder from the view?

### ISSUE THREAD

**Issue by kevinmkchin** [AirGuanZ/imgui-filebrowser#18]
I can't seem to navigate through the folders

**Comment by AirGuanZ** [comment]
use double click to enter a folder. when no folder is selected, click 'ok' to return the current folder

this behavior is a little counter-intuitively. i'll think about how to improve it.

**Comment by AirGuanZ** [comment]
hi, i have made a change to the behavior of directory selection. please check the 'Usage' section in README.

**Comment by kevinmkchin** [comment]
Hey, thanks for doing that. I appreciate it. I tried editing your code to make it work as well, but I think I will just use your version.
