### ISSUE TITLE
`#include <version>` requires C++20

### ISSUE THREAD

**Issue by claudeha** [AirGuanZ/imgui-filebrowser#22]
It seems that some C++20 crept in with `#include <version>`:

https://en.cppreference.com/w/cpp/utility#Language_support

> The header `<version>`  supplies implementation-dependent information about the C++ standard  library (such as the version number and release date). It also defines  the library feature-test macros. | **(since C++20)**

(emphasis mine)

Compilation currently fails with C++17:

```
$ g++ -std=c++17 ...
...
../../imgui-filebrowser/imfilebrowser.h:37:10: fatal error: version: No such file or directory
 #include <version>
          ^~~~~~~~~
compilation terminated.
```

I have an interest in compiling my program on Debian Buster (current stable), whose `g++` does not support full C++20 (only an incomplete `-std=c++2a`), so I will investigate and see if this include is strictly necessary, or what can be done to replace it.

```
$ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by AirGuanZ** [comment]
Tks! Already fixed in the newest version.
Including this is actually not necessary since __cpp_lib_char8_t (that's why I use <version>) will be defined in [library facility](https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros#C.2B.2B17).
