### ISSUE TITLE
Flags are not modifiable after construction

### ISSUE THREAD

**Issue by cianjinks** [AirGuanZ/imgui-filebrowser#25]
Title says it all. I am wondering why there is no `ImGui::FileBrowser::GetFlags()` function or a `ImGui::FileBrowser::SetFlags(ImGuiFileBrowserFlags flags)` function? Instead it can only be done upon construction of the browser object.

For my case I want to be able to save and load things and when saving I want to enable the entering of a file name and when loading I do not. To do so should I be creating a different file browser for each?

**Comment by AirGuanZ** [comment]
We can implement the same function with assignment operator. For example:
```cpp
FileBrowser fileBrowser;
// ... do other stuff
fileBrowser = FileBrowser(ImGuiFileBrowserFlags_SelectDirectory);
```
The disadvantage is that `title`, `dialog size` and `current directory` are not kept with the new browser.  However, we can set it manually:
```cpp
FileBrowser fileBrowser;
// do other stuff
const auto dir = fileBrowser.GetPwd();
fileBrowser = FileBrowser(ImGuiFileBrowserFlags_SelectDirectory);
fileBrowser.SetPwd(dir);
```
I will consider adding a `SetFlags` soon.

**Comment by cianjinks** [comment]
Thank you, I'll consider using that for now
