### ISSUE TITLE
Capitalized extensions are ignored

### ISSUE THREAD

**Issue by MonJamp** [AirGuanZ/imgui-filebrowser#27]
For example if a file has the extension `.TXT`. Calling `SetTypeFilters({".txt", ".TXT"})`, won't show any files with capitalized extensions.

**Comment by AirGuanZ** [comment]
Hi,

Thanks for telling me this.

I succeeded to reproduce the problem. When multiple file type filters are set, only one of them will be applied and you can select it on the file browser panel. That seems to be a little inconvenient if you want to apply all filters at the same time. So I have added three small features:
* A special filter ".*", meaning all file extensions
* An auto-generated filter containing all other filters. For example, `SetTypeFilters({".txt", ".TXT"})` results in `{".txt,.TXT", ".txt", ".TXT"}`, and the first option matches with both ".txt" and ".TXT". Note that this is a special filter -- user-provided `.txt,.TXT` won't work like that.
* Filename is case-insensitive on Windows, so filters are also case-insensitive on Windows now and duplicated ones will be merged automatically.

As for your problem,  `SetTypeFilters({".txt", ".TXT"})` should work as expected (with the newest version of filebrowser).

**Comment by MonJamp** [comment]
Thank you! Works as expected like you said.
