### ISSUE TITLE
All dont work

### ISSUE THREAD

**Issue by NekoMazix** [AirGuanZ/imgui-filebrowser#35]
https://youtu.be/5e0aAzQGBs4

**Comment by AirGuanZ** [comment]
please paste your use code of the file browser

**Comment by NekoMazix** [comment]
HRESULT __stdcall hkPresent(IDXGISwapChain* pSwapChain, UINT SyncInterval, UINT Flags)
{
	if (!init)
	{
		if (SUCCEEDED(pSwapChain->GetDevice(__uuidof(ID3D11Device), (void**)& pDevice)))
		{
			pDevice->GetImmediateContext(&pContext);
			DXGI_SWAP_CHAIN_DESC sd;
			pSwapChain->GetDesc(&sd);
			window = sd.OutputWindow;
			ID3D11Texture2D* pBackBuffer;
			pSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), (LPVOID*)& pBackBuffer);
			pDevice->CreateRenderTargetView(pBackBuffer, NULL, &mainRenderTargetView);
			pBackBuffer->Release();
			oWndProc = (WNDPROC)SetWindowLongPtr(window, GWLP_WNDPROC, (LONG_PTR)WndProc);
			InitImGui();
			init = true;
		}

		else
			return oPresent(pSwapChain, SyncInterval, Flags);
	}

	// (optional) set browser properties

	ImGui::FileBrowser fileDialog;
	// (optional) set browser properties
	fileDialog.SetTitle(xorstr("Select Congfig!"));

	fileDialog.SetTypeFilters({ ".txt" });

	style();

	if (GetAsyncKeyState(VK_END)) {
		kiero::shutdown();
		return 0;
	}

	if (GetAsyncKeyState(VK_INSERT) & 1) {
		menu = !menu;
	}


	if (menu) {
		ImGui_ImplDX11_NewFrame();
		ImGui_ImplWin32_NewFrame();
		ImGui::NewFrame();
		analhooks();
		if (ImGui::Begin("dummy window"))
		{
			// open file dialog when user clicks this button
			if (ImGui::Button("open file dialog"))
				fileDialog.Open();
		}
		ImGui::Text("\n");
		ImGui::Text(xorstr("Application average %.3f ms/frame (%.1f FPS)"), 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		ImGui::End();
		fileDialog.Display();
		if (fileDialog.HasSelected())
		{
			std::cout << "Selected filename" << fileDialog.GetSelected().string() << std::endl;
			fileDialog.ClearSelected();
		}
		ImGui::Render();

		pContext->OMSetRenderTargets(1, &mainRenderTargetView, NULL);
		ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
	}
	return oPresent(pSwapChain, SyncInterval, Flags);
}

**Comment by NekoMazix** [comment]
HRESULT __stdcall hkPresent(IDXGISwapChain* pSwapChain, UINT SyncInterval, UINT Flags)
{
	if (!init)
	{
		if (SUCCEEDED(pSwapChain->GetDevice(__uuidof(ID3D11Device), (void**)& pDevice)))
		{
			pDevice->GetImmediateContext(&pContext);
			DXGI_SWAP_CHAIN_DESC sd;
			pSwapChain->GetDesc(&sd);
			window = sd.OutputWindow;
			ID3D11Texture2D* pBackBuffer;
			pSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), (LPVOID*)& pBackBuffer);
			pDevice->CreateRenderTargetView(pBackBuffer, NULL, &mainRenderTargetView);
			pBackBuffer->Release();
			oWndProc = (WNDPROC)SetWindowLongPtr(window, GWLP_WNDPROC, (LONG_PTR)WndProc);
			InitImGui();
			init = true;
		}

		else
			return oPresent(pSwapChain, SyncInterval, Flags);
	}

	// (optional) set browser properties

	ImGui::FileBrowser fileDialog;
	// (optional) set browser properties
	fileDialog.SetTitle(xorstr("Select Config!"));

	fileDialog.SetTypeFilters({ ".txt" });

	if (GetAsyncKeyState(VK_END)) {
		kiero::shutdown();
		return 0;
	}

	if (GetAsyncKeyState(VK_INSERT) & 1) {
		menu = !menu;
	}


	if (menu) {
		ImGui_ImplDX11_NewFrame();
		ImGui_ImplWin32_NewFrame();
		ImGui::NewFrame();
		analhooks();
		if (ImGui::Begin("dummy window"))
		{
			// open file dialog when user clicks this button
			if (ImGui::Button("open file dialog"))
				fileDialog.Open();
		}
		ImGui::Text("\n");
		ImGui::Text(xorstr("Application average %.3f ms/frame (%.1f FPS)"), 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		ImGui::End();
		fileDialog.Display();
		if (fileDialog.HasSelected())
		{
			std::cout << "Selected filename" << fileDialog.GetSelected().string() << std::endl;
			fileDialog.ClearSelected();
		}
		ImGui::Render();

		pContext->OMSetRenderTargets(1, &mainRenderTargetView, NULL);
		ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
	}
	return oPresent(pSwapChain, SyncInterval, Flags);
}

**Comment by AirGuanZ** [comment]
try moving the definition of dialog variable out of the rendering loop. the dialog object is stateful and the current usage recreates it every frame.
