### ISSUE TITLE
请问怎么才能设置成多选

### ISSUE THREAD

**Issue by 168762321** [AirGuanZ/imgui-filebrowser#37]
请问怎么设置成多选。这是为写的代码，但是失败了
if (show_upload_images_window){
            fileDialog.Open();
          
            fileDialog.Display();
            if(fileDialog.HasSelected())
            {
               
                fileDialog.GetMultiSelected();
                fileDialog.Close();
            }
            
        }

**Comment by AirGuanZ** [comment]
1. 创建`fileDialog`的时候在构造函数中传`ImGuiFileBrowserFlags_MultipleSelection`
2. 在readme的示例中，不论`show_upload_images_window`是否为`true`，每帧都要运行以下代码：
```
fileDialog.Display();
if(fileDialog.HasSelected())
{
    fileDialog.GetMultiSelected();
    fileDialog.Close();
}
```
`fileDialog`会维护自身是否处于打开的状态。

**Comment by 168762321** [comment]
真是太感谢了。已经解决这个问题了。
