### ISSUE TITLE
Read access violation when setting type filters on release

### ISSUE THREAD

**Issue by naorliron2** [AirGuanZ/imgui-filebrowser#40]
Can't seem to replicate consistently, But when using the file browser I will sometimes get an "Exception thrown at 0x00007FF776436552 in ProjectName.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFF8."

the call stack shows that this is caused by SetTypeFilter().
![Capture (2)](https://user-images.githubusercontent.com/60105589/155997248-14111246-1f98-409a-877b-dfe555466fc4.PNG)

Also important to note that this only happens in release

**Comment by AirGuanZ** [comment]
Hi,
The only call to `std::vector::clear` in `SetTypeFilters` is at its beginning for clearing old filters, and all accesses to this vector object in other functions are read-only. Therefore the cause of the crash seems to be at another location (which breaks the internal states of `typeFilters_`).
BTW, you can use `data breakpoint` to find the code that unexpectedly changes the pointer in the string object.

**Comment by AirGuanZ** [comment]
That makes the problem hard to track. Since the internal state of `typeFilters_` may be broken by other memory writes in the program. Sorry for not being able to provide some useful help.

**Comment by AirGuanZ** [comment]
I'll close this issue since it has been inactive for a long time. Feel free to reopen it if needed.
