### ISSUE TITLE
File browser turns gray instead of background with recent ImGui version.

### ISSUE THREAD

**Issue by Centicus1000** [AirGuanZ/imgui-filebrowser#42]
Hi,
first of: I love your work!

I recently updated the ImGui files in my project to the newest version. This seems to have broken the "gray turning" (not sure what this is called in ImGui-slang). Instead of the background, the file browser turns gray. This seems to be only a visual bug.

This is a screenshot of your "Getting Started"-Example code, with the old ImGui-files (v1.67):
<img width="1302" alt="screenshot-1" src="https://user-images.githubusercontent.com/55696718/168165170-5c4238cd-59ce-4524-9e2f-0cdb947c9dd8.png">

And this is a screenshot of the same code, but using the most recent ImGui (v1.88):
<img width="1302" alt="screenshot-2" src="https://user-images.githubusercontent.com/55696718/168165205-0452bde7-e6d2-4579-9170-37f624545122.png">

I'm having the same issue on Mac and Windows. Do you know what the reason for this could be?
Thank you. <3

**Comment by AirGuanZ** [comment]
Hi,
I only found v1.87 on the official release page of `dear-imgui`. With that version, the file browser works as usual. Could you please tell me where to download the v1.88？Thanks.

**Comment by Centicus1000** [comment]
Oh sorry, I got the ImGui files from the master branch, where it says v1.88 in the imgui.h file.

But I figured out the problem: I forgot to update my backend files. My bad.

Updating those fixed the problem. For v1.87 and v1.88.
Thank you.
