### ISSUE TITLE
Mouse position bug on multiple monitors

### ISSUE THREAD

**Issue by meemknight** [AirGuanZ/imgui-filebrowser#44]
It seems like if you use this library on a pc with multiple monitors with different resolutions the mouse position is not correct on the other display.
I don't know if this bus is specific to this library or to ImGui.

![image](https://user-images.githubusercontent.com/36445656/173233464-3cadb784-f2a1-4699-a47e-d6e2dfb159ff.png)

**Comment by AirGuanZ** [comment]
Hi,
The file browser doesn't manage cursor-widget intersection itself. So it's very likely to be a ImGui bug.

**Comment by meemknight** [comment]
Ok, I'll make a bug report on the ImGui repo. Thank you.
