### ISSUE TITLE
Not working with gamepad

### ISSUE THREAD

**Issue by Flashby2** [AirGuanZ/imgui-filebrowser#47]
It seems that the selection does not work with the gamepad, all is good on my side it must be related to the ImGui::IsItemClicked

**Comment by AirGuanZ** [comment]
Hi,
Sorry for the late reply.  I am currently not using a gamepad in my imgui development environment, so I am not familiar with how to interact with imgui using a gamepad. Do you think replacing IsItemClicked & MouseButton_Left directly with gamepad buttons would be sufficient?
Any suggestion is welcome.

**Comment by audetto** [comment]
Hi

What is impossible to do is to manage folders: they seem to require a double click which I cannot generate via a gamepad.

For a file it is possible: one button to select it and then with OK I can accept it.

If it were possible to navigate without the need of a double click, then I think it would work automatically with the gamepad.

**Comment by AirGuanZ** [comment]
This issue should be solved by #55. Feel free to reopen it if needed.
