### ISSUE TITLE
Select several files with Shift key pressed

### ISSUE THREAD

**Issue by kfjahnke** [AirGuanZ/imgui-filebrowser#50]
Hi! I have a proposition:
I'd like to see different behaviour when Shift is pressed, re. what happens when Ctrl is pressed. Shift+Click normally selects all files in the range from the previous selection to the currently clicked entry, so it can be used to quickly select several files. Making no difference between Shift and Ctrl is unexpected. With the current behaviour, obtaining large selections is cumbersome. I'd also like a way to quickly select all listed files (like Ctrl+A).

**Comment by AirGuanZ** [comment]
Great suggestion. I will do it soon.

**Comment by kfjahnke** [comment]
Great! I like your approach using std::filesystem and keeping it simple and straightforward. My project is an image viewer, and it's often necessary to select several or all images in a folder, e.g. for a slide show, so without easy access to selecting multiple files I can't use your code as it is. Thanks for your prompt reply!

**Comment by AirGuanZ** [comment]
Done. Please try the newest version.

**Comment by kfjahnke** [comment]
I tried it:
The multiple-select superficially works here, but the selection it passes back on calling `fileDialog.GetMultiSelected()` contains files which should have been filtered out - e.g. if  I set the filter to only show .jpg and .png files with `fileDialog.SetTypeFilters({ ".png", ".jpg" });`, the selection contains .xcf and all kinds of other files as well: everything where the file name fits alphabetically between the start and end of the selection. Apart from the missing discrimination, all seems well.

**Comment by AirGuanZ** [comment]
Thanks for your feedback. Fix is submitted.

**Comment by AirGuanZ** [comment]
btw, `ctrl + a` hasn't been supported. will do it soon

**Comment by kfjahnke** [comment]
Hey, that was quick :)
Now the filter works. Thanks! And, yes, Ctrl+A would be nice to have, too!
While you're at it, maybe you could add accepting the current selection by pressing Return and trigger cancel with Escape? I think this is what users will expect - at least I did ;)
Or am I doing something wrong? The only flag I pass is `ImGuiFileBrowserFlags_MultipleSelection`

**Comment by AirGuanZ** [comment]
`ImGuiFileBrowserFlags_CloseOnEsc`: cancel with Escape.
`ImGuiFileBrowserFlags_ConfirmOnEnter`: confirm when enter is pressed and at least one item is selected.
`Ctrl + A` is also supported in the newest version. (only when multi-selection is enabled)

**Comment by kfjahnke** [comment]
I tried it here, and all three additions work as expected. Thank you very much!
