### ISSUE TITLE
Wrong characters when entering a name with special characters

### ISSUE THREAD

**Issue by MaikelChan** [AirGuanZ/imgui-filebrowser#54]
First of all, amazing file browser, works great!

I'm having a small issue though. When selecting a file with special characters, `GetSelected()` returns the name correctly. But when entering a new name with special characters (window created with `ImGuiFileBrowserFlags_EnterNewFilename`), `GetSelected()` will break those characters.

As a workaround, I fixed the problem by changing line 665 like this:
`selectedFilenames_ = { std::filesystem::u8path(inputNameBuf_->data()) };`

But probably there's a better way to do it that also takes into account other `InputText`, like when creating a new folder (didn't test if it works fine).

Greetings!

**Comment by KTorresgit** [comment]
Your workaround using `std::filesystem::u8path(inputNameBuf_->data())` is a good approach, as it ensures that the string is correctly converted into a UTF-8 encoded path, which can handle special characters properly. However, you mentioned that there might be other areas where similar issues could arise, such as when creating a new folder?

**Comment by AirGuanZ** [comment]
Nice fix! I'll take a look.

**Comment by AirGuanZ** [comment]
Hi, I have merged the fix. Thank you!

**Comment by KTorresgit** [comment]
Good day! Thanks for the clarification. The issue you're describing could indeed affect any input field that handles file or folder names with special characters. Since the _input handling_ for creating new folders is likely similar to that for entering a new file name, the same UTF-8 handling concerns would apply.
