### ISSUE TITLE
Conflicts with numeric_limits<T>

### ISSUE THREAD

**Issue by SebGlaw** [AirGuanZ/imgui-filebrowser#56]
https://github.com/AirGuanZ/imgui-filebrowser/blob/b8fedfb673a4e13413bcac789d4c0b63bc19d948/imfilebrowser.h#L1203

The precompiler has replaced my calls to numeric_limits<T>::min(), numeric_limits<T>::max() with min and max from minwindef.h. 

I could solve it with using: 

#define NOMINMAX
#include <windows.h>
#undef NOMINMAX

**Comment by AirGuanZ** [comment]
Thank you for your feedback. This issue with Windows.h is notorious (as mentioned in the last section of README). Please checkout the latest version.
