### ISSUE TITLE
SetCurrentDirectory redefined in win-api

### ISSUE THREAD

**Issue by ThFriedrich** [AirGuanZ/imgui-filebrowser#57]
Using the function SetCurrentDirectory() seems to cause an issue on Windows.
Using 
``` fileDialog.SetCurrentDirectory("."); ```
gives the error:
```"SetCurrentDirectoryA" is not a member of "ImGui::FileBrowser".```

Apparently processenv.h of the win api includes:
```
SetCurrentDirectoryW(
    _In_ LPCWSTR lpPathName
    );
#ifdef UNICODE
#define SetCurrentDirectory  SetCurrentDirectoryW
#else
#define SetCurrentDirectory  SetCurrentDirectoryA
#endif // !UNICODE
```
which redefines the function. Not sure if I am doing something wrong? Apreciate any feedback & pointers.

**Comment by AirGuanZ** [comment]
This happens when `Windows.h` is included prior to `imfilebrowser.h`. SetCurrentDirectory & GetCurrentDirectory have been renamed to SetDirectory & GetDirectory in the latest version. Please check that.

**Comment by ThFriedrich** [comment]
The fix seems to work. Thanks for the quick update. Cheers
