### ISSUE TITLE
ImGui::End() seems to be missing in readme.md

### ISSUE THREAD

**Issue by xkxsxkx** [AirGuanZ/imgui-filebrowser#6]
ImGui::Begin(name);
    if(ImGui::Begin("dummy window"))
    {
        // open file dialog when user clicks this button
        if(ImGui::Button("open file dialog"))
            fileDialog.Open();
        ImGui::End(); //add here
    }
ImGui::End();

**Comment by AirGuanZ** [comment]
Hi,
There is no `ImGui::Begin(name);` at the beginning in README. So the last `ImGui::End();` is matched with  `if(ImGui::Begin("dummy window"))`, which seems to be ok.
