### ISSUE TITLE
Support for selecting folder too

### ISSUE THREAD

**Issue by pratikone** [AirGuanZ/imgui-filebrowser#8]
This is a very cool project and I am planning to use it. I see this can act as file selector, but is there a way to provide functionality to just select a folder ? Otherwise I will have to do the processing at my end.

**Comment by AirGuanZ** [comment]
You can pass `ImGuiFileBrowserFlags_SelectDirectory` to the contructor:
```cpp
ImGui::FileBrowser browser(ImGuiFileBrowserFlags_SelectDirectory);
```

**Comment by pratikone** [comment]
Oh yeah. thanks for explaining that. I will close this bug. you can add this more explicitly to the readme
